name: CI for backend
on:
  push:
    branches: [main]
    paths-ignore:
      - "frontend/**"
      - "docs/**"
  pull_request:
    paths-ignore:
      - "frontend/**"
      - "docs/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v19
      - uses: DeterminateSystems/magic-nix-cache-action@v13
      - name: Cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            backend -> target
      - name: CI
        run: nix develop .#backend -c bash -lc 'cd backend && just ci'
