name: CI for frontend
on:
  push:
    branches: [main]
    paths-ignore:
      - "backend/**"
      - "docs/**"
  pull_request:
    paths-ignore:
      - "backend/**"
      - "docs/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v19
      - uses: DeterminateSystems/magic-nix-cache-action@v13
      - name: CI
        run: nix develop .#frontend -c bash -lc 'cd frontend && pnpm install --frozen-lockfile && just ci'
