name: lint for toml and yaml
on:
  push:
    branches: [main]
    paths-ignore:
      - "**"
      - "!**/**.yaml"
      - "!**/**.yml"
      - "!**/**.toml"
  pull_request:
    paths-ignore:
      - "**"
      - "!**/**.yaml"
      - "!**/**.yml"
      - "!**/**.toml"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v19
      - uses: DeterminateSystems/magic-nix-cache-action@v13
      - name: CI
        run: nix develop -c just lint-ci
